name: BarQi
options:
  bundleIdPrefix: com.taher
  createIntermediateGroups: true
targets:
  BarQi:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources
        name: BarQi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taher.BarQi
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: Sources/Info.plist
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
        ENABLE_PREVIEWS: YES
